In [2]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/leenaomrani/Desktop/vestiaire_case/Dataset 3/DIM_VC_USR_CUSTOMER.csv')

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (13,14,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [7]:
df

,ID_CUSTOMER,ID_GENDER,DATE_NEW_BUYER,DATE_NEW_SELLER,DATE_CREATION,DATE_INACTIVE,DATE_LAST_LOGIN,ID_COUNTRY,DEVICE_BRAND,REGISTRATION_DEVICE,...,SELLER_SEGMENT,REGISTRATION_UTM_CAMPAIGN_NON_PERSISTENT,REGISTRATION_UTM_SOURCE_NON_PERSISTENT,REGISTRATION_UTM_MEDIUM_NON_PERSISTENT,REGISTRATION_UTM_CAMPAIGN_30D_PERSISTENT,REGISTRATION_UTM_SOURCE_30D_PERSISTENT,REGISTRATION_UTM_MEDIUM_30D_PERSISTENT,REGISTRATION_MARKETING_CHANNEL_NON_PERSISTENT,REGISTRATION_MARKETING_CHANNEL_30D_PERSISTENT,IS_ACCOUNT_VERIFIED
0,17257021,2,NaN,NaN,2022-06-27T16:52:12Z,NaN,2022-06-27T16:52:13Z,74,other,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
1,9117724,2,NaN,NaN,2019-12-07T10:37:28Z,NaN,2019-12-07T10:37:29Z,223,other,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,8862262,2,NaN,NaN,2019-10-14T03:40:34Z,NaN,2019-10-14T03:40:35Z,223,other,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,6757583,1,2018-04-28,2022-05-29,2018-04-25T23:26:26Z,NaN,2023-03-31T21:32:55Z,57,other,desktop,...,Low quality repeater,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,14268557,0,NaN,NaN,2021-10-21T20:11:19Z,NaN,2021-10-21T20:11:20Z,74,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,20857179,2,NaN,NaN,2023-04-18T14:17:23Z,NaN,2023-04-18T14:17:52Z,105,iOS,smartphone,...,NaN,it_it_organic_freelisting_buyer_all_all,google,organic,it_it_organic_freelisting_buyer_all_all,google,organic,seo_freelisting,seo_freelisting,True
19996,91661,2,2013-04-15,NaN,2011-03-24T12:56:00Z,NaN,2023-01-28T23:28:14Z,74,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
19997,16812898,2,NaN,NaN,2022-05-08T17:25:01Z,NaN,2022-05-08T17:25:07Z,81,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
19998,11347815,3,NaN,NaN,2020-12-22T23:43:49Z,NaN,2020-12-22T23:43:51Z,223,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
19999,8264108,1,NaN,NaN,2019-03-26T22:12:27Z,NaN,2020-11-04T21:13:42Z,74,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [3]:
df1=pd.read_csv('/Users/leenaomrani/Desktop/vestiaire_case/Dataset 3/DIM_VC_USR_CUSTOMER(1).csv')

/opt/anaconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (13,14,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [8]:
df1

,ID_CUSTOMER,ID_GENDER,DATE_NEW_BUYER,DATE_NEW_SELLER,DATE_CREATION,DATE_INACTIVE,DATE_LAST_LOGIN,ID_COUNTRY,DEVICE_BRAND,REGISTRATION_DEVICE,...,SELLER_SEGMENT,REGISTRATION_UTM_CAMPAIGN_NON_PERSISTENT,REGISTRATION_UTM_SOURCE_NON_PERSISTENT,REGISTRATION_UTM_MEDIUM_NON_PERSISTENT,REGISTRATION_UTM_CAMPAIGN_30D_PERSISTENT,REGISTRATION_UTM_SOURCE_30D_PERSISTENT,REGISTRATION_UTM_MEDIUM_30D_PERSISTENT,REGISTRATION_MARKETING_CHANNEL_NON_PERSISTENT,REGISTRATION_MARKETING_CHANNEL_30D_PERSISTENT,IS_ACCOUNT_VERIFIED
0,18847998,2,NaN,NaN,2022-12-08T17:48:15Z,NaN,2023-02-08T11:12:44Z,188,iOS,smartphone,...,NaN,(not set),(not set),(not set),(not set),(not set),(not set),direct,direct,True
1,15217469,2,NaN,NaN,2022-01-04T22:58:30Z,NaN,2022-01-04T22:58:36Z,222,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,20506751,2,NaN,NaN,2023-04-02T03:32:39Z,NaN,2023-04-02T03:32:41Z,223,Android,smartphone,...,NaN,(not set),(not set),(not set),(not set),(not set),(not set),direct,direct,True
3,19000682,2,NaN,NaN,2022-12-25T14:53:00Z,NaN,2022-12-27T10:31:37Z,105,iOS,smartphone,...,NaN,(not set),(not set),(not set),(not set),(not set),(not set),direct,direct,True
4,8358059,2,NaN,NaN,2019-04-25T16:27:20Z,NaN,2019-04-25T16:27:21Z,97,other,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103360,15851546,2,NaN,NaN,2022-02-27T17:54:38Z,NaN,2023-03-05T08:23:10Z,223,iOS,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
103361,9534703,2,NaN,NaN,2020-03-07T18:06:55Z,NaN,2020-03-07T18:06:56Z,222,other,desktop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
103362,4470256,2,NaN,NaN,2017-01-11T13:03:44Z,NaN,2018-08-25T19:15:43Z,222,iOS,smartphone,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
103363,17476064,2,NaN,NaN,2022-07-25T04:39:34Z,NaN,2022-07-25T04:39:36Z,188,other,desktop,...,NaN,1st_purchase,criteo_sg,retargeting,1st_purchase,criteo_sg,retargeting,retargeting_p,retargeting_p,True
103364,664027,2,NaN,NaN,2013-07-21T10:07:49Z,2014-01-08T16:37:22Z,2019-05-31T13:21:13Z,195,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [9]:
df['ID_CUSTOMER'].nunique()

20000

In [7]:
import pandas as pd

# Create a DataFrame with the given data
data = {
    'GMV': [1819207, 1567321],
    'User_Segment': ['engaged', 'Hibernating'],
    'Count': [453, 4131]
}

df = pd.DataFrame(data)

# Define the user segments and their counts
segments = ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
            'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
            'Potentially engaged', 'Lost']

counts = [4131, 6599, 2692, 2494, 913, 637, 785, 453, 484, 212, 1]

# Add missing segments with GMV value and count of 0
df = df.reindex(segments, fill_value=0)
df['Count'] = counts

# Calculate the total GMV and total count
total_gmv = df['GMV'].sum()
total_count = df['Count'].sum()

# Calculate the distribution of GMV and count by user segment
df['GMV_Distribution'] = df['GMV'] / total_gmv * 100
df['Count_Distribution'] = df['Count'] / total_count * 100

# Print the result
print(df)

                     GMV User_Segment  Count  GMV_Distribution  \
Hibernating            0            0   4131               NaN
Inactive 6m-12m        0            0   6599               NaN
Dormant 6m             0            0   2692               NaN
At risk                0            0   2494               NaN
Need attention         0            0    913               NaN
Highly engaged         0            0    637               NaN
About to sleep         0            0    785               NaN
Engaged                0            0    453               NaN
At high risk           0            0    484               NaN
Potentially engaged    0            0    212               NaN
Lost                   0            0      1               NaN

                     Count_Distribution
Hibernating                   21.292717
Inactive 6m-12m               34.013711
Dormant 6m                    13.875573
At risk                       12.855007
Need attention                 4.705943
Highly engaged                 3.283336
About to sleep                 4.046183
Engaged                        2.334931
At high risk                   2.494717
Potentially engaged            1.092727
Lost                           0.005154

In [15]:
# For 2022 

import pandas as pd

# Create a DataFrame with the given data
data = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count': [4131, 6599, 2692, 2494, 913, 637, 785, 453, 484, 212, 0]
}

df = pd.DataFrame(data)

# Calculate the total count
total_count = df['Count'].sum()

# Calculate the contribution of each segment to the GMV
df['GMV_Contribution'] = df['Count'] / total_count * 1819207

# Print the result
print(df)

           User_Segment  Count  GMV_Contribution
0           Hibernating   4131     387378.562732
1       Inactive 6m-12m   6599     618811.700670
2            Dormant 6m   2692     252438.414639
3               At risk   2494     233871.250412
4        Need attention    913      85615.257268
5        Highly engaged    637      59733.755619
6        About to sleep    785      73612.242010
7               Engaged    453      42479.421186
8          At high risk    484      45386.401443
9   Potentially engaged    212      19879.994021
10                 Lost      0          0.000000

In [16]:
import pandas as pd

# Create a DataFrame with the given data
data = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count': [13843, 1428, 718, 796, 490, 411, 407, 272, 164, 126, 1]
}

df = pd.DataFrame(data)

# Calculate the total count
total_count = df['Count'].sum()

# Calculate the contribution of each segment to the GMV
df['GMV_Contribution'] = df['Count'] / total_count * 1567321

# Print the result
print(df)

           User_Segment  Count  GMV_Contribution
0           Hibernating  13843      1.162973e+06
1       Inactive 6m-12m   1428      1.199686e+05
2            Dormant 6m    718      6.032035e+04
3               At risk    796      6.687326e+04
4        Need attention    490      4.116570e+04
5        Highly engaged    411      3.452878e+04
6        About to sleep    407      3.419273e+04
7               Engaged    272      2.285116e+04
8          At high risk    164      1.377791e+04
9   Potentially engaged    126      1.058547e+04
10                 Lost      1      8.401163e+01

In [23]:
#2021
import pandas as pd

# Create a DataFrame with the given data
data = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count': [13843, 1428, 718, 796, 490, 411, 407, 272, 164, 126, 1]
}

df = pd.DataFrame(data)

# Calculate the total count
total_count = df['Count'].sum()

# Calculate the contribution of each segment to the GMV
df['GMV_Contribution_2021'] = df['Count'] / total_count * 1567321

# Sort the DataFrame by GMV distribution in descending order
df.sort_values('GMV_Contribution_2021', ascending=False, inplace=True)

# Reset the index
df.reset_index(drop=True, inplace=True)

# Format the GMV distribution to remove scientific notation
df['GMV_Contribution_2021'] = df['GMV_Contribution_2021'].apply(lambda x: '{:,.0f}'.format(x))

# Print the result
print(df)

           User_Segment  Count GMV_Contribution_2021
0           Hibernating  13843             1,162,973
1       Inactive 6m-12m   1428               119,969
2               At risk    796                66,873
3            Dormant 6m    718                60,320
4        Need attention    490                41,166
5        Highly engaged    411                34,529
6        About to sleep    407                34,193
7               Engaged    272                22,851
8          At high risk    164                13,778
9   Potentially engaged    126                10,585
10                 Lost      1                    84

In [21]:
#2022
import pandas as pd

# Create a DataFrame with the given data
data = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count': [4131, 6599, 2692, 2494, 913, 637, 785, 453, 484, 212, 0]
}

df = pd.DataFrame(data)

# Calculate the total count
total_count = df['Count'].sum()

# Calculate the contribution of each segment to the GMV
df['GMV_Contribution_2022'] = df['Count'] / total_count * 1819207

# Format the GMV distribution to remove scientific notation
df['GMV_Contribution_2022'] = df['GMV_Contribution_2022'].apply(lambda x: '{:,.0f}'.format(x))

# Print the result
print(df)

           User_Segment  Count GMV_Contribution_2022
0           Hibernating   4131               387,379
1       Inactive 6m-12m   6599               618,812
2            Dormant 6m   2692               252,438
3               At risk   2494               233,871
4        Need attention    913                85,615
5        Highly engaged    637                59,734
6        About to sleep    785                73,612
7               Engaged    453                42,479
8          At high risk    484                45,386
9   Potentially engaged    212                19,880
10                 Lost      0                     0

In [25]:
import pandas as pd

# Create the first dataframe for 2022
data_2022 = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'Dormant 6m', 'At risk', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count_2022': [4131, 6599, 2692, 2494, 913, 637, 785, 453, 484, 212, 0],
    'GMV_Contribution_2022': [387379, 618812, 252438, 233871, 85615, 59734, 73612, 42479, 45386, 19880, 0]
}

df_2022 = pd.DataFrame(data_2022)

# Create the second dataframe for 2021
data_2021 = {
    'User_Segment': ['Hibernating', 'Inactive 6m-12m', 'At risk', 'Dormant 6m', 'Need attention',
                     'Highly engaged', 'About to sleep', 'Engaged', 'At high risk',
                     'Potentially engaged', 'Lost'],
    'Count_2021': [13843, 1428, 796, 718, 490, 411, 407, 272, 164, 126, 1],
    'GMV_Contribution_2021': [1162973, 119969, 66873, 60320, 41166, 34529, 34193, 22851, 13778, 10585, 84]
}

df_2021 = pd.DataFrame(data_2021)

# Merge the dataframes based on "User_Segment" column
merged_df = pd.merge(df_2022, df_2021, on='User_Segment')

# Print the result
print(merged_df)

           User_Segment  Count_2022  GMV_Contribution_2022  Count_2021  \
0           Hibernating        4131                 387379       13843
1       Inactive 6m-12m        6599                 618812        1428
2            Dormant 6m        2692                 252438         718
3               At risk        2494                 233871         796
4        Need attention         913                  85615         490
5        Highly engaged         637                  59734         411
6        About to sleep         785                  73612         407
7               Engaged         453                  42479         272
8          At high risk         484                  45386         164
9   Potentially engaged         212                  19880         126
10                 Lost           0                      0           1

    GMV_Contribution_2021
0                 1162973
1                  119969
2                   60320
3                   66873
4                   41166
5                   34529
6                   34193
7                   22851
8                   13778
9                   10585
10                     84

In [28]:
merged_df

,User_Segment,Count_2022,GMV_Contribution_2022,Count_2021,GMV_Contribution_2021
0,Hibernating,4131,387379,13843,1162973
1,Inactive 6m-12m,6599,618812,1428,119969
2,Dormant 6m,2692,252438,718,60320
3,At risk,2494,233871,796,66873
4,Need attention,913,85615,490,41166
5,Highly engaged,637,59734,411,34529
6,About to sleep,785,73612,407,34193
7,Engaged,453,42479,272,22851
8,At high risk,484,45386,164,13778
9,Potentially engaged,212,19880,126,10585
10,Lost,0,0,1,84

In [27]:
merged_df.to_csv('/Users/leenaomrani/Desktop/vestiaire_case/Dataset 3/customer_segmentation.csv')